### ISSUE TITLE
add sanity check after pre-rendering

### ISSUE THREAD

**Issue by krancour** [akuity/bookkeeper#158]
@evgeny-goldin has suggested a worthwhile improvement.

If the pre-rendering phase were to complete and yielded _nothing_, this is almost certainly a sign of a major problem.

Rather than blindly continuing with that result, this should raise an error and cause bookkeeper CLI or action to return non-0 unless some flag like `--empty` is set to explicitly indicate a tolerance for this possibility.

**Comment by jessesuen** [comment]
Argo CD has the same protection for the same reasons. It refuses to prune everything in the app unless explicitly opt-ed in with the option `allowEmpty: true`
